name: bcp
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - scipy
  - meshplot
  - plotly
  - igl
  - wildmeshing
  - polyfempy
  - pyyaml
  - pytorch
  - torchvision
  - cpuonly
  - pip
  - pip:
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - torch-geometric
    - quadpy==0.13.0
